name: Auto-merge

on: [push]

jobs:
  merge:
    name: merge to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: srt32/git-actions@v0.0.3
        with: 
          args: git status
