name: Auto-merge

on:
  push:
    branches: 
      - master

jobs:
  merge:
    name: merge to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: dev
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Merge
        run: git merge -X theirs origin/master
      - name: Push
        run: |
          git config --global user.email "max.kuklin@eu.m3.com"
          git config --global user.name "Max Kuklin"
          git remote rm origin
          git remote add origin https://acnot:${{ secrets.ACCESS_TOKEN }}@github.com/acnot/acnot.github.io.git
          git push origin dev
#      - uses: srt32/git-actions@v0.0.3
#        with: 
#          args: git status
