name: Auto-merge

on:
  push:
    branches: 
      - master

jobs:
  merge:
    name: merge to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: dev
          submodules: true
      - name: Merge
        run: |
          git merge -X theirs origin/master
          git remote rm origin
          git remote add origin https://acnot:${{ secrets.ACCESS_TOKEN }}@github.com/acnot/acnot.github.io.git
          git push origin dev

