name: Auto-merge

on:
  push:
    branches: 
      - master

jobs:
  merge:
    name: merge to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: dev
          submodules: true
      - name: Merge
        run: git merge -X theirs origin/master
      - name: Push
        run: |
          git -c http.extraheader="AUTHORIZATION: basic ${{ github.token }}" push origin
#      - uses: srt32/git-actions@v0.0.3
#        with: 
#          args: git status
